
== 이 책에 대하여

_비트코인 개발 철학(Bitcoin Development Philosophy)_은 이미 작업 증명(Proof-of-Work), 블록 생성, 트랜잭션 생애 주기 등의 개념과 과정에 대해 기본적인 이해를 갖춘 비트코인 개발자를 위한 가이드입니다. 
이 책은 비트코인의 설계에서의 트레이드오프(trade-offs)와 철학에 대한 깊은 이해를 통해 개발자들이 한 단계 더 성장할 수 있도록 돕습니다. 
또한 지난 10년 넘게 진행된 비트코인 개발과 공개적인 논쟁에서 얻어진 중요한 교훈들을 흡수하는 데 도움이 될 것이며, 
새로운 아이디어들(좋은 것과 나쁜 것 모두)을 평가할 수 있는 유용한 맥락을 제공할 것입니다.


:oldstyle: {xrefstyle}
:xrefstyle: full
<<탈중앙화(decentralization)>>::
<<무신뢰성(trustlessness)>>::
<<프라이버시(privacy)>>::
<<유한공급(finitesupply)>>::
<<업그레이드(upgrading)>>::
<<적대적 사고(adversarialthinking)>>::
<<오픈소스(opensource)>>::
<<확장성(scaling)>>::
<<위기 상황에서의 대처(whenshithitsthefan)>>::
<<부록 A(appendixdiscussion)>>::
<<부록 B(appendixbuild)>>:: {empty}

:xrefstyle: {oldstyle}

여러분의 피드백과 기여는 언제나 환영합니다! 빌드 및 기여에 대한 안내는 <<부록 B(appendixbuild)>>에서 확인할 수 있습니다.

== 기대할 수 있는 것들

앞서 언급했듯이, 이 책은 비트코인 개발자를 위한 실용적인 가이드입니다. 
하지만 비트코인은 매우 넓고 복잡한 주제이기 때문에 이 책에서 모든 측면을 다 다룰 수는 없습니다. 
이 책을 통해 여러분이 개발 활동을 시작하는 데 필요한 기능들을 논의하고, 스스로 더 깊이 탐구할 수 있는 기회를 제공하고자 합니다.
비트코인에는 많은 사람들이 관여하고 있으며, 그들 중 일부는 상반된 의견을 가지고 있습니다. 
여기서 여러분은 서로 모순된 아이디어를 표현하는 자료를 찾을 수 있을 것입니다. 
그러나 우리는 항상 의견보다는 사실에 기반을 두려고 노력합니다.

== 이 책은 누가 썼나요?

이 책의 주요 저자는 칼레 로젠바움(Kalle Rosenbaum)이며, 린네아 로젠바움(Linnéa Rosenbaum)이 공동 저자로 기여했습니다. 
이 작업은 비트코인 개발을 배우고자 하는 개발자를 위한 교육 프로그램을 운영하는 개발 센터인 https://learning.chaincode.com/[체인코드 랩스(Chaincode Labs)]의 의뢰와 자금 지원을 받아 작성되었습니다.
칼레는 https://rosenbaum.se/book/[_Grokking Bitcoin_](Manning Publications)의 저자이며, 숙련된 소프트웨어 개발자입니다. 
그는 2015년부터 비트코인 관련 개발을 전문적으로 해왔습니다.

린네아는 전자 시스템 박사 학위를 보유하고 있습니다. 
그녀는 https://konsensus.network/product/lilla-boken-om-bitcoin/[_The Little Bitcoin Book_]의 스웨덴어 번역자이며, 
https://konsensus.network/product/sverige-bitcoinstandarden/[_The Bitcoin Standard_]의 공동 번역자입니다. 
또한 스웨덴 비트코인 협회의 이사로 활동하고 있습니다. 그녀의 배경은 펌웨어 개발에 있으며, 최근에는 소프트웨어 개발로 전환하였습니다.


== 이 책은 어떻게 구성되어 있나요?

이 책은 각 장이 비트코인과 관련된 중요한 주제를 다루는 방식으로 구성되어 있습니다. 
각 장은 해당 주제에 대한 관련 정보를 안내하며, 우리가 추천하는 읽을거리나 시청할 수 있는 기사나 동영상으로 연결되는 링크와 QR 코드가 추가되어 있습니다. 
보고된 자료들은 오랜 기간 비트코인 개발을 연구한 사람들이 작성한 것입니다.

링크는 우리가 통제할 수 없는 외부 자원으로 연결됩니다. 따라서 링크된 기사들은 이 저장소에 로컬로 저장해 두었으며, 어디서 가져왔는지와 언제 복사되었는지에 대한 정보도 함께 기록했습니다. 
자료들은 별도의 문서 (sources/sources.adoc)에 수집되어 있으며, 각 장에서 링크된 내용에 따라 정리되어 있습니다. 장에서 제공된 링크들은 원본 출처로 연결되며, 이는 온라인에서 찾을 수 있습니다.
그러나 인터넷 연결이 없거나 링크가 끊어지거나 정보가 심각하게 변경된 것처럼 보이는 경우, 로컬에서 그 내용을 읽을 수 있습니다.

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

== About this book

_Bitcoin Development Philosophy_ is a guide for Bitcoin developers
who already understand the basics of concepts and processes such as Proof-of-Work, block
building, and the transaction life cycle, and who want to level up by
gaining a deeper understanding of Bitcoin's design trade-offs and
philosophy. It should help new developers absorb the most important
lessons of over a decade of Bitcoin development and public debate, while providing them with
a useful context for evaluating new ideas (good ones and bad ones!).

Table of contents overview:

:oldstyle: {xrefstyle}
:xrefstyle: full
<<decentralization>>::
<<trustlessness>>::
<<privacy>>::
<<finitesupply>>::
<<upgrading>>::
<<adversarialthinking>>::
<<opensource>>::
<<scaling>>::
<<whenshithitsthefan>>::
<<appendixdiscussion>>::
<<appendixbuild>>:: {empty}

:xrefstyle: {oldstyle}

Your feedback and contributions are most welcome! Instructions for
building and contributing can be found in <<appendixbuild>>.

=== What to expect?

As stated above, this is a practical guide for Bitcoin developers. However, Bitcoin is a broad and complex subject and we couldn't possibly cover all of its aspects here. With this book, we
hope to discuss the necessary features to get your development activity started as well as to enable you to further explore it on your own.

There are lots of people involved in Bitcoin; as some of them have opposing opinions, here you may find
resources that express contradictory ideas. However, we always
attempt to stick to the domain of facts, where opinions do not matter.

=== Who wrote this?

The main author of this book is Kalle Rosenbaum, and Linnéa Rosenbaum contributed as a co-author. This work
was commissioned and funded by https://learning.chaincode.com/[Chaincode Labs], a development center that runs educational
programs for developers who want to learn about Bitcoin development.

Kalle is the author of https://rosenbaum.se/book/[_Grokking Bitcoin_] (Manning Publications) and is a 
seasoned software developer. He's been working professionally with Bitcoin-related development since 
2015.

Linnéa has a Ph.D. in Electronic Systems. She is the Swedish translator of https://konsensus.network/product/lilla-boken-om-bitcoin/[_The Little Bitcoin Book_] and co-translator of https://konsensus.network/product/sverige-bitcoinstandarden/[_The Bitcoin Standard_].  She is also on the board of the Swedish Bitcoin Association. Her background is in firmware development with a recent shift towards software development.



=== How is this organized?

The book is sectioned into chapters, each covering a pivotal topic within Bitcoin. Every
chapter guides you through the relevant information related to the chapter's focus, with the addition of links and QR codes that will take you to articles or
videos that we recommend reading or watching. The reported material was written by individuals who have
studied Bitcoin development for a long time.

The links refer to external resources on platforms we cannot
control. We have therefore saved the linked articles locally in this
repository, along with the information on where it was copied from and when. The
resources are collected in link:sources/sources.html[a separate
document] (`sources/sources.adoc`) and organized by the chapter they are
linked to. The links found in the chapters refer to the original
sources, which should be found online, but in case you don't have an internet connection, the links
appear dead, or the information seems severely changed, you can read the
content locally instead.

